# Generated by Django 4.1.2 on 2022-10-05 07:22

from django.db import migrations, models
import registration_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=registration_profile.models.code_generator, max_length=5
                    ),
                ),
            ],
        ),
    ]
