# Generated by Django 4.1.1 on 2022-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationprofile",
            name="aware_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("search_engine", "Search Engine"),
                    ("friend", "Friend"),
                    ("online_ad", "Online Ads"),
                    ("other", "Other"),
                ],
                max_length=250,
            ),
        ),
    ]
