version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/adrien-la-boudi/week7day3:latest
    ports:
      - 8001:8000 # Opens port 8000 on the container's side, sends data to port 8001 on local machine side
    volumes:
      - ./backend:/backend
    env_file:
      - ./envs/dev.env
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/dev.env
    ports:
      - 5555:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db: