# Generated by Django 4.1.1 on 2022-10-06 07:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=users.models.user_directory_path
            ),
        ),
    ]
