# Generated by Django 4.1.1 on 2022-10-05 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("shirt", "Shirt"),
                            ("pants", "Pants"),
                            ("jacket", "Jacket"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("s", "Small"), ("m", "Medium"), ("l", "Large")],
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("darkblue", "Darkblue"),
                            ("green", "Green"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                (
                    "available",
                    models.IntegerField(default=0, help_text="Available quantity"),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
