# Generated by Django 4.1.1 on 2022-10-06 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_suspiciousorders"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reviewer",
            field=models.ManyToManyField(
                related_name="suspicious_orders",
                through="orders.SuspiciousOrders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
